[font]
size = 10

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[colors.primary]
background = "#292b2e"
foreground = "#d3dae3"

[colors.cursor]
text = "#212026"
cursor = "#d3dae3"

[colors.vi_mode_cursor]
text = "#212026"
cursor = "#d3dae3"

[colors.selection]
text = "#d3dae3"
background = "#5d4d7a"

[colors.search.matches]
foreground = "#212026"
background = "#5d4d7a"

[colors.search.focused_match]
foreground = "#212026"
background = "#5d4d7a"

[colors.footer_bar]
foreground = "#212026"
background = "#5d4d7a"

[colors.hints.start]
foreground = "#212026"
background = "#5d4d7a"

[colors.hints.end]
foreground = "#212026"
background = "#5d4d7a"

[colors.normal]
black = "#212026"
red = "#da4453"
green = "#27ae60"
yellow = "#dc752f"
blue = "#4f97d7"
magenta = "#bc6ec5"
cyan = "#2aa1ae"
white = "#d3dae3"

[colors.bright]
black = "#686868"
red = "#da4453"
green = "#27ae60"
yellow = "#dc752f"
blue = "#4f97d7"
magenta = "#bc6ec5"
cyan = "#2aa1ae"
white = "#d3dae3"

[[colors.indexed_colors]]
index = 16
color = "#4f97d7"

[[colors.indexed_colors]]
index = 17
color = "#9a9aba"
